### ISSUE TITLE
Mistral concurrency problem

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2370]
st2 version 1.2.0.8

workflow `test.yaml.meta` of a test pack named `epsilon`:
```
---
  description: "Testing concurrency"
  runner_type: "mistral-v2"
  tags: []
  enabled: true
  pack: "epsilon"
  entry_point: "workflows/test.yaml"
  uid: "action:epsilon:test"
  parameters:
    skip_notify:
      default: []
      type: "array"
      description: "List of tasks to skip notifications for."
    task:
      type: "string"
      description: "The name of the task to run for reverse workflow."
    workflow:
      type: "string"
      description: "The name of the workflow to run if the entry_point is a workbook of many workflows. The name should be in the format \"<pack_name>.<action_name>.<workflow_name>\". If entry point is a workflow or a workbook with a si
      default: "epsilon.test.main"
      immutable: true
    conc:
      default: 5
      type: "integer"
      description: "Concurrency"
    context:
      default: {}
      type: "object"
      description: "Additional workflow inputs."
  ref: "epsilon.test"
  name: "test"
```

Workflow `test.yaml` itself:
```
---
version: '2.0'
name: epsilon.test

workflows:
  main:
    type: direct
    input:
      - conc
      - hosts_array:
        - hostname01
        - hostname02
        - hostname03
        - hostname04
        - hostname05
        - hostname06
        - hostname07
        - hostname08
        - hostname09
        
    tasks:

      run_flows:
        # [262, 215]
        workflow: enumerate
        concurrency: <% $.conc %>
        with-items: host in <% $.hosts_array %>
        input:
          name: <% $.host %>

  enumerate:
    type: direct
    input:
      - name
    
    tasks:
      say:
        # [86, 399]
        action: core.local
        input:
          cmd: 'echo <% $.name %>'
```

This ends up with the following result:

![image](https://cloud.githubusercontent.com/assets/4997180/12242053/6491e5be-b85c-11e5-9f2b-a80f957de9eb.png)

Rendering this mistral's feature completely useless.

**Comment by jjm** [comment]
I've just tried concurrency with the number hardcode to 1 and it looked like it work. Did you get any further debugging this?

**Comment by emptywee** [comment]
Yeah, basically concurrency set to 1 = no concurrency. It is the only way it works reliably.

**Comment by emptywee** [comment]
https://bugs.launchpad.net/mistral/+bug/1536415
I believe this has finally got fixed in mistral. Waiting for it to be included in the future versions of Stackstorm.

**Comment by emptywee** [comment]
@jjm @manasdk claims that 1.3.1.15 (the latest for now) has this patch included. I am going to update soon and verify.

**Comment by jjm** [comment]
Thanks, I was really wanting to run a workflow against one one host at a time. 

I should upgrade next week.

**Comment by manasdk** [comment]
@m4dcoder Looks like @emptywee is still seeing this issue even with 1.3.2

**Comment by m4dcoder** [comment]
@emptywee: i'm not able to reproduce the problem. are you running this workflow on a single system or multiple systems?  please go to /opt/openstack/mistral and check which branch of mistral is installed.  i provided the output of my execution for reference here.

```vagrant@arkham:~/st2$ st2 execution get 56cb85431e2e241aad09f344 -dj
{
    "action": {
        "ref": "sandbox.concurrency"
    }, 
    "context": {
        "user": "stanley"
    }, 
    "end_timestamp": "2016-02-22T22:01:51.849825Z", 
    "id": "56cb85431e2e241aad09f344", 
    "liveaction": {
        "action": "sandbox.concurrency", 
        "callback": {}, 
        "id": "56cb85431e2e241aad09f343", 
        "parameters": {}, 
        "runner_info": {
            "hostname": "arkham", 
            "pid": 6771
        }
    }, 
    "result": {
        "__env": {
            "__actions": {
                "st2.action": {
                    "st2_context": {
                        "auth_token": "b25d311e7d7d4823a6b8197993d6095e", 
                        "endpoint": "http://127.0.0.1:9101/v1/actionexecutions", 
                        "notify": {}, 
                        "parent": {
                            "execution_id": "56cb85431e2e241aad09f344", 
                            "user": "stanley"
                        }, 
                        "skip_notify_tasks": []
                    }
                }
            }, 
            "st2_action_api_url": "http://127.0.0.1:9101/v1", 
            "st2_execution_id": "56cb85431e2e241aad09f344", 
            "st2_liveaction_id": "56cb85431e2e241aad09f343"
        }, 
        "__execution": {
            "id": "e613a5b3-912c-4c2b-924b-620290aa75fe", 
            "input": {
                "conc": 5, 
                "hosts_array": [
                    "hostname01", 
                    "hostname02", 
                    "hostname03", 
                    "hostname04", 
                    "hostname05", 
                    "hostname06", 
                    "hostname07", 
                    "hostname08", 
                    "hostname09", 
                    "hostname10"
                ]
            }, 
            "params": {
                "env": {
                    "__actions": {
                        "st2.action": {
                            "st2_context": {
                                "auth_token": "b25d311e7d7d4823a6b8197993d6095e", 
                                "endpoint": "http://127.0.0.1:9101/v1/actionexecutions", 
                                "notify": {}, 
                                "parent": {
                                    "execution_id": "56cb85431e2e241aad09f344", 
                                    "user": "stanley"
                                }, 
                                "skip_notify_tasks": []
                            }
                        }
                    }, 
                    "st2_action_api_url": "http://127.0.0.1:9101/v1", 
                    "st2_execution_id": "56cb85431e2e241aad09f344", 
                    "st2_liveaction_id": "56cb85431e2e241aad09f343"
                }
            }, 
            "spec": {
                "input": [
                    "conc", 
                    {
                        "hosts_array": [
                            "hostname01", 
                            "hostname02", 
                            "hostname03", 
                            "hostname04", 
                            "hostname05", 
                            "hostname06", 
                            "hostname07", 
                            "hostname08", 
                            "hostname09", 
                            "hostname10"
                        ]
                    }
                ], 
                "name": "main", 
                "tasks": {
                    "task1": {
                        "action": "st2.action", 
                        "concurrency": "<% $.conc %>", 
                        "input": {
                            "parameters": {
                                "cmd": "echo <% $.host %>"
                            }, 
                            "ref": "core.local"
                        }, 
                        "name": "task1", 
                        "publish": {
                            "hosts": "<% task(task1).result.select($.stdout) %>"
                        }, 
                        "type": "direct", 
                        "version": "2.0", 
                        "with-items": "host in <% $.hosts_array %>"
                    }
                }, 
                "type": "direct", 
                "version": "2.0"
            }
        }, 
        "__tasks": {}, 
        "conc": 5, 
        "extra": {
            "state": "SUCCESS", 
            "state_info": null
        }, 
        "hosts": [
            "hostname01", 
            "hostname02", 
            "hostname03", 
            "hostname04", 
            "hostname05", 
            "hostname06", 
            "hostname07", 
            "hostname08", 
            "hostname09", 
            "hostname10"
        ], 
        "hosts_array": [
            "hostname01", 
            "hostname02", 
            "hostname03", 
            "hostname04", 
            "hostname05", 
            "hostname06", 
            "hostname07", 
            "hostname08", 
            "hostname09", 
            "hostname10"
        ], 
        "task1": [
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname01", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname02", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname03", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname04", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname05", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname06", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname07", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname08", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname09", 
                "succeeded": true
            }, 
            {
                "failed": false, 
                "return_code": 0, 
                "stderr": "", 
                "stdout": "hostname10", 
                "succeeded": true
            }
        ], 
        "tasks": [
            {
                "created_at": "2016-02-22 22:01:40.284015", 
                "id": "618adb4d-c3b0-4a90-a8b8-850eaa0f350f", 
                "input": null, 
                "name": "task1", 
                "published": {
                    "hosts": [
                        "hostname01", 
                        "hostname02", 
                        "hostname03", 
                        "hostname04", 
                        "hostname05", 
                        "hostname06", 
                        "hostname07", 
                        "hostname08", 
                        "hostname09", 
                        "hostname10"
                    ]
                }, 
                "result": [
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname01", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname02", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname03", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname04", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname05", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname06", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname07", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname08", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname09", 
                        "succeeded": true
                    }, 
                    {
                        "failed": false, 
                        "return_code": 0, 
                        "stderr": "", 
                        "stdout": "hostname10", 
                        "succeeded": true
                    }
                ], 
                "state": "SUCCESS", 
                "state_info": null, 
                "updated_at": "2016-02-22 22:01:46.761895", 
                "workflow_execution_id": "e613a5b3-912c-4c2b-924b-620290aa75fe", 
                "workflow_name": "sandbox.concurrency.main"
            }
        ]
    }, 
    "start_timestamp": "2016-02-22T22:01:39.683363Z", 
    "status": "succeeded"
}```

**Comment by manasdk** [comment]
@m4dcoder - I confirmed that the mistral install was correct by asking @emptywee to provide me with the SHA for the HEAD commit on `/opt/openstack/mistral`

**Comment by m4dcoder** [comment]
@emptywee, then please ping me on slack at your convenience and we can troubleshoot further online.

**Comment by emptywee** [comment]
I think this issue can be safely closed as fixed.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1467752816003473
