### ISSUE TITLE
Creating a rule with month: "*" fails

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2730]
Specifying the month in a CronTimer rule results in an Internal Server Error. The below rule code works fine without the `month: "*"` line.

```
---
name: "remote_test"
pack: "default"
description: ""
enabled: true

trigger:
    type: "core.st2.CronTimer"
    parameters:
        minute: "3"
        hour: "15"
        day: "*"
        month: "*"
        day_of_week: "*"

action:
    ref: "core.remote_sudo"
    parameters:
        cmd: "whoami"
        hosts: "myhost"
```

Try to load it

```
$ st2 rule create remote_test.yaml
ERROR: 500 Server Error: Internal Server Error
MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/v1/rules
```

We can see what happens in the logs here:

```
==> /plogs/st2/st2api.log <==
2016-06-03 15:26:55,881 140553046116784 ERROR hooks [-] API call failed: 'NoneType' object has no attribute 'update'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/api/base.py", line 230, in callfunction
    result = f(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/rbac/decorators.py", line 85, in func_wrapper
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/rules.py", line 96, in post
    increment_trigger_ref_count(rule_api=rule)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/triggers.py", line 202, in increment_trigger_ref_count
    Trigger.update(trigger_db, inc__ref_count=1)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/base.py", line 200, in update
    cls._get_impl().update(model_object, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 178, in update
    return instance.update(**kwargs)
AttributeError: 'NoneType' object has no attribute 'update' (_exception_data={},_exception_class='AttributeError',_exception_message="'NoneType' object has no attribute 'update'")

<snip>

2016-06-03 15:26:55,887 140553046116784 INFO hooks [-] 972bc83e-e8ab-4e6c-bbc7-7145d8deed68 - POST /v1/rules result={
    "faultstring": "Internal Server Error"
} (result='{\n    "faultstring": "Internal Server Error"\n}',request_id='972bc83e-e8ab-4e6c-bbc7-7145d8deed68',status_code='500 Internal Server Error',remote_addr='127.0.0.1',path='/v1/rules',method='POST')
```

**Comment by Kami** [comment]
Thanks for reporting this, I will look into it tomorrow.

From the error it actually seems related to a bad state in DB and not "*" value for month per say, but I could be wrong and I will see when I look into it and try to reproduce it,

**Comment by Kami** [comment]
Just a heads up - I was able to reproduce it and I'm looking into it.

**Comment by Kami** [comment]
Looks like it's some weird issue when querying and Python types are unicode (and it doesn't always happen :/)

```python
{u'month': u'*', u'day': u'*', u'minute': u'3', u'hour': u'15'}
ipdb> Trigger.query(parameters=parameters)
[]
ipdb> parameters={'month': '*', 'day': '*', 'minute': '3', 'hour': '15'}
ipdb> Trigger.query(parameters=parameters)
[<TriggerDB: TriggerDB(description=None, id=575559840640fd0df24cdac2, name="9f95dcf2-d125-45f6-b2e1-fcaed2667778", pack="core", parameters={u'hour': u'15', u'day': u'*', u'minute': u'3', u'month': u'*'}, ref_count=0, type="core.st2.CronTimer", uid="trigger:core:9f95dcf2-d125-45f6-b2e1-fcaed2667778:e24eb4b23e53d023769d26b74010318a")>]
```

**Comment by codyaray** [comment]
Thanks!

**Comment by Kami** [comment]
After more digging it looks like a bug lies inside pymongo. I'm trying to come up with a work-around but it turns out it's quite hard - there also appears to be a bug with query set cache so even if I disable it I get an exception back :/

**Comment by Kami** [comment]
@codyaray I just merged #2732 (as noted in that PR, the work-around / hack is terrible, but that's the only option we have right now).

I did confirm it myself, but can you please also confirm that this change fixes the issue for you as well (you will also need to delete "bad rules" aka ones without corresponding TriggerDB objects from the database, you might need to do that use `mongo` shell / repl)?

Once you confirm it, I will go ahead and close this issue.

**Comment by codyaray** [comment]
This was discovered on my prod cluster, so I'm unlikely to update to an unstable version since I have a workaround (i.e., my rules don't actually _have_ to specify the month). However, I'll try to test/reproduce in my dev environment.

**Comment by codyaray** [comment]
@Kami Most of my cron triggers didn't fire again this morning. Is this related? From the logs:

```
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:219ce49f-ae70-4491-8d23-9d2889be8dc8:7b2e3f06c16a3583662b5b67b3d0046f', 'parameters': {u'minute': 50, u'hour': 8, u'day_of_week': u'1-5'}, 'description': None, 'ref_count': 1, 'name': u'219ce49f-ae70-4491-8d23-9d2889be8dc8', 'type': u'core.st2.CronTimer', 'id': '574755ec59e5f11c4198bc0f', 'pack': u'core'})
```

**Comment by Kami** [comment]
@codyaray Yeah, I forgot to say that this bug is (as far as I know) causing this issue as well since it follows the same code-path and utilizes the same function.

In short - it should fix this issue as well.

**Comment by codyaray** [comment]
Well. In that case, I think I might just upgrade. Can't have failing jobs in my prod cluster. :)

**Comment by codyaray** [comment]
Upgraded to 1.5dev-92 and confirmed that this fixed the reported issue with `month: "*"`. Can I just delete all the rules using the CLI and re-sync them to effectively removed the bad ones from the DB?

**Comment by Kami** [comment]
If it works, you can, yes. If it doesn't you will need to resort to Mongo shell / repl.

**Comment by codyaray** [comment]
@Kami deleting and re-adding apparently did not fix. Got "Trigger not found" again this morning. 

Just ran `db.trigger_d_b.remove()` on mongo master, `sudo st2ctl restart` on each node, and then ran `st2ctl reload --register-all` (and cleaned up errors until it finished successfully; still need to finish #2701]). I guess we'll see how tomorrow morning goes. :)

**Comment by codyaray** [comment]
Closing this issue and moving back to #2715 where the existing problem may or may not still exist.
