### ISSUE TITLE
Tracking issue: st2rulesengine and st2notifier are at 100% CPU

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3506]
st2 version: 2.2.1

Mick McGrath on support will provide us logs to troubleshoot.

**Comment by mickmcgrath13** [comment]
So, the CPU being too high was taken care of by deleting some unused & problematic triggers from `db.trigger_d_b`.

Now, we still have an enormous delay in chatops, and the `st2.notifiers.work` queue in rabbitmq is still growing a lot faster than I'd expect it to (and not really getting cleared)...

Here is a snippet of the DEBUG logs for `/var/log/st2/st2notifier.log`:
```
2017-06-22 17:05:37,895 140357569377936 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aac30271fb24e06469e3b. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:26:08.749825+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:26:09', 'updated_at': None, 'id': u'7ba66943-eabe-42c9-8743-8bbb47560d79', 'workflow_execution_id': u'6b36d436-c45a-46f5-a947-9cffd397086f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aac30271fb24e06469e3c', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - {id_: 594aac30271fb24e06469e3d, trace_tag: execution-594aac30271fb24e06469e3b}
2017-06-22 17:05:40,107 140357569378096 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aabbc271fb24e06469e36. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:24:12.265215+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:24:12', 'updated_at': None, 'id': u'45e8b6c7-1dbd-4c42-abb6-9fc1bc9943a7', 'workflow_execution_id': u'0ef15a6c-acc1-4213-9907-f2fb64247c3e', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aabbc271fb24e06469e37', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - {id_: 594aabbc271fb24e06469e38, trace_tag: execution-594aabbc271fb24e06469e36}
2017-06-22 17:05:41,198 140357570222992 DEBUG channel [-] Closed channel #1
2017-06-22 17:05:42,231 140357569376976 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aae95271fb24e06469e5d. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:36:21.705631+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:36:22', 'updated_at': None, 'id': u'fb2d593d-96ae-422c-b011-a9bf0382768e', 'workflow_execution_id': u'8948f34a-43f6-4f2a-8d70-ab134de0f38c', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aae95271fb24e06469e5e', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - {id_: 594aae95271fb24e06469e5f, trace_tag: execution-594aae95271fb24e06469e5d}
2017-06-22 17:05:42,236 140357570222352 DEBUG channel [-] Closed channel #1
2017-06-22 17:05:44,359 140357570223792 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aadcf271fb24e06469e51. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:33:03.279802+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:33:03', 'updated_at': None, 'id': u'650960ac-10f4-403e-b966-298fe7e01107', 'workflow_execution_id': u'93d81384-d30c-461f-ad31-95c1ebf15b9b', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aadcf271fb24e06469e52', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - {id_: 594aadcf271fb24e06469e53, trace_tag: execution-594aadcf271fb24e06469e51}
2017-06-22 17:05:44,361 140357570223152 DEBUG channel [-] Closed channel #1
2017-06-22 17:05:46,563 140357569376656 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aaa8c271fb24e06469e11. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:19:08.615634+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:19:09', 'updated_at': None, 'id': u'65521f3b-5be9-4bac-8cdb-d42727e74ec7', 'workflow_execution_id': u'1f8a77c7-57a5-4081-9413-68e4fab5f05d', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aaa8c271fb24e06469e12', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - {id_: 594aaa8c271fb24e06469e13, trace_tag: execution-594aaa8c271fb24e06469e11}
```

The context is that while that action (`default.sre-demo-error-notifier`) was being created, it got stuck somehow and needed to be cancelled.  I just don't know how to kill it, now :P

**Comment by mickmcgrath13** [comment]
..checked my CPU this morning... it's back at 100% for `st2notifier` and `st2rulesengine`

**Comment by bigmstone** [comment]
@lakshmi-kannan @m4dcoder @arma Is this related to some of the issues we fixed just before 2.3 release? I want to say we were experiencing the same thing on st2cicd, but I don't remember the details.

**Comment by mickmcgrath13** [comment]
So, this happened: https://github.com/StackStorm/st2/issues/3513
...and now our chatops is back up and running it seems...

The [aforementioned issue](https://github.com/StackStorm/st2/issues/3506#issuecomment-310535573) of the `default.sre-demo-error-notifier` is still happening, though (every 5 seconds, there's this:
```
2017-06-23 12:00:56,618 140434365064848 DEBUG notifier [-] Processing liveaction 594aad3f271fb24e06469e47 (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19838}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:30:39.507751+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:30:40', 'updated_at': None, 'workflow_execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'd145eb29-502b-491e-85fc-9e016139060f'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aad3f271fb24e06469e47', 'end_timestamp': '2017-06-21 17:31:15.088020+00:00'})
2017-06-23 12:00:56,642 140434365064848 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,645 140434365066608 DEBUG notifier [-] Processing liveaction 594aabbc271fb24e06469e36 (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19683}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:24:12.265215+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:24:12', 'updated_at': None, 'workflow_execution_id': u'0ef15a6c-acc1-4213-9907-f2fb64247c3e', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'45e8b6c7-1dbd-4c42-abb6-9fc1bc9943a7'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'0ef15a6c-acc1-4213-9907-f2fb64247c3e'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aabbc271fb24e06469e36', 'end_timestamp': '2017-06-21 17:25:01.544718+00:00'})
2017-06-23 12:00:56,665 140434365064848 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aad3f271fb24e06469e47. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:30:39.507751+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:30:40', 'updated_at': None, 'id': u'd145eb29-502b-491e-85fc-9e016139060f', 'workflow_execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aad3f271fb24e06469e48', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,665 140434365064848 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:30:39.507751+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:30:40', 'updated_at': None, 'id': u'd145eb29-502b-491e-85fc-9e016139060f', 'workflow_execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aad3f271fb24e06469e48', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,665 140434365064848 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,669 140434365064848 DEBUG channel [-] Channel open
2017-06-23 12:00:56,670 140434365066608 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,671 140434365064848 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,680 140434365066608 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aabbc271fb24e06469e36. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:24:12.265215+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:24:12', 'updated_at': None, 'id': u'45e8b6c7-1dbd-4c42-abb6-9fc1bc9943a7', 'workflow_execution_id': u'0ef15a6c-acc1-4213-9907-f2fb64247c3e', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aabbc271fb24e06469e37', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,680 140434365066608 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:24:12.265215+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:24:12', 'updated_at': None, 'id': u'45e8b6c7-1dbd-4c42-abb6-9fc1bc9943a7', 'workflow_execution_id': u'0ef15a6c-acc1-4213-9907-f2fb64247c3e', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aabbc271fb24e06469e37', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,680 140434365066608 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,681 140434365066608 DEBUG channel [-] Channel open
2017-06-23 12:00:56,682 140434365066608 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,707 140434365066608 DEBUG notifier [-] Processing liveaction 594aac30271fb24e06469e3b (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19725}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:26:08.749825+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:26:09', 'updated_at': None, 'workflow_execution_id': u'6b36d436-c45a-46f5-a947-9cffd397086f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'7ba66943-eabe-42c9-8743-8bbb47560d79'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'6b36d436-c45a-46f5-a947-9cffd397086f'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aac30271fb24e06469e3b', 'end_timestamp': '2017-06-21 17:27:50.726908+00:00'})
2017-06-23 12:00:56,724 140434365066608 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,734 140434365066608 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aac30271fb24e06469e3b. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:26:08.749825+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:26:09', 'updated_at': None, 'id': u'7ba66943-eabe-42c9-8743-8bbb47560d79', 'workflow_execution_id': u'6b36d436-c45a-46f5-a947-9cffd397086f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aac30271fb24e06469e3c', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,734 140434365066608 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:26:08.749825+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:26:09', 'updated_at': None, 'id': u'7ba66943-eabe-42c9-8743-8bbb47560d79', 'workflow_execution_id': u'6b36d436-c45a-46f5-a947-9cffd397086f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aac30271fb24e06469e3c', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,734 140434365066608 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,735 140434365066608 DEBUG channel [-] Channel open
2017-06-23 12:00:56,736 140434365066608 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,763 140434365066608 DEBUG notifier [-] Processing liveaction 594aaa8c271fb24e06469e11 (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19869}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:19:08.615634+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:19:09', 'updated_at': None, 'workflow_execution_id': u'1f8a77c7-57a5-4081-9413-68e4fab5f05d', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'65521f3b-5be9-4bac-8cdb-d42727e74ec7'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'1f8a77c7-57a5-4081-9413-68e4fab5f05d'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aaa8c271fb24e06469e11', 'end_timestamp': '2017-06-21 17:22:04.652571+00:00'})
2017-06-23 12:00:56,777 140434365065488 DEBUG notifier [-] Processing liveaction 594aadcf271fb24e06469e51 (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19704}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:33:03.279802+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:33:03', 'updated_at': None, 'workflow_execution_id': u'93d81384-d30c-461f-ad31-95c1ebf15b9b', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'650960ac-10f4-403e-b966-298fe7e01107'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'93d81384-d30c-461f-ad31-95c1ebf15b9b'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aadcf271fb24e06469e51', 'end_timestamp': '2017-06-21 17:33:55.773204+00:00'})
2017-06-23 12:00:56,784 140434365065648 DEBUG notifier [-] Processing liveaction 594aae95271fb24e06469e5d (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19815}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:36:21.705631+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:36:22', 'updated_at': None, 'workflow_execution_id': u'8948f34a-43f6-4f2a-8d70-ab134de0f38c', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'fb2d593d-96ae-422c-b011-a9bf0382768e'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'8948f34a-43f6-4f2a-8d70-ab134de0f38c'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aae95271fb24e06469e5d', 'end_timestamp': '2017-06-21 17:38:35.707609+00:00'})
2017-06-23 12:00:56,788 140434365066608 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,788 140434365065008 DEBUG notifier [-] Processing liveaction 594aad6a271fb24e06469e4c (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19896}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:31:22.605979+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:31:23', 'updated_at': None, 'workflow_execution_id': u'c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'23d9afa7-94be-4b36-b6d8-db153652cb9b'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aad6a271fb24e06469e4c', 'end_timestamp': '2017-06-21 17:32:57.669612+00:00'})
2017-06-23 12:00:56,805 140434365065488 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,823 140434365065648 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,844 140434365065008 DEBUG notifier [-] Applying 0 post_run policies
2017-06-23 12:00:56,862 140434365066608 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aaa8c271fb24e06469e11. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:19:08.615634+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:19:09', 'updated_at': None, 'id': u'65521f3b-5be9-4bac-8cdb-d42727e74ec7', 'workflow_execution_id': u'1f8a77c7-57a5-4081-9413-68e4fab5f05d', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aaa8c271fb24e06469e12', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,862 140434365066608 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:19:08.615634+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:19:09', 'updated_at': None, 'id': u'65521f3b-5be9-4bac-8cdb-d42727e74ec7', 'workflow_execution_id': u'1f8a77c7-57a5-4081-9413-68e4fab5f05d', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aaa8c271fb24e06469e12', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,862 140434365066608 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,867 140434365066608 DEBUG channel [-] Channel open
2017-06-23 12:00:56,868 140434365066608 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,872 140434365065488 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aadcf271fb24e06469e51. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:33:03.279802+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:33:03', 'updated_at': None, 'id': u'650960ac-10f4-403e-b966-298fe7e01107', 'workflow_execution_id': u'93d81384-d30c-461f-ad31-95c1ebf15b9b', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aadcf271fb24e06469e52', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,872 140434365065488 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:33:03.279802+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:33:03', 'updated_at': None, 'id': u'650960ac-10f4-403e-b966-298fe7e01107', 'workflow_execution_id': u'93d81384-d30c-461f-ad31-95c1ebf15b9b', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aadcf271fb24e06469e52', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,872 140434365065488 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,872 140434365065648 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aae95271fb24e06469e5d. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:36:21.705631+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:36:22', 'updated_at': None, 'id': u'fb2d593d-96ae-422c-b011-a9bf0382768e', 'workflow_execution_id': u'8948f34a-43f6-4f2a-8d70-ab134de0f38c', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aae95271fb24e06469e5e', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,873 140434365065648 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:36:21.705631+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:36:22', 'updated_at': None, 'id': u'fb2d593d-96ae-422c-b011-a9bf0382768e', 'workflow_execution_id': u'8948f34a-43f6-4f2a-8d70-ab134de0f38c', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aae95271fb24e06469e5e', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,873 140434365065648 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,874 140434365065648 DEBUG channel [-] Channel open
2017-06-23 12:00:56,874 140434365065488 DEBUG channel [-] Channel open
2017-06-23 12:00:56,875 140434365065648 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,877 140434365065488 DEBUG channel [-] Closed channel #1
2017-06-23 12:00:56,877 140434365065008 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 594aad6a271fb24e06469e4c. Payload - {'status': u'canceled', 'start_timestamp': '2017-06-21 17:31:22.605979+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:31:23', 'updated_at': None, 'id': u'23d9afa7-94be-4b36-b6d8-db153652cb9b', 'workflow_execution_id': u'c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aad6a271fb24e06469e4d', 'action_name': u'default.sre-demo-error-notifier'}. TraceContext - None
2017-06-23 12:00:56,877 140434365065008 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': None, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2017-06-21 17:31:22.605979+00:00', 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'created_at': u'2017-06-21 17:31:23', 'updated_at': None, 'id': u'23d9afa7-94be-4b36-b6d8-db153652cb9b', 'workflow_execution_id': u'c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'workflow_name': u'default.sre-demo-error-notifier'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_ref': u'default.sre-demo-error-notifier', 'runner_ref': u'mistral-v2', 'execution_id': '594aad6a271fb24e06469e4d', 'action_name': u'default.sre-demo-error-notifier'}})
2017-06-23 12:00:56,877 140434365065008 DEBUG channel [-] using channel_id: 1
2017-06-23 12:00:56,878 140434365065008 DEBUG channel [-] Channel open
2017-06-23 12:00:56,879 140434365065008 DEBUG channel [-] Closed channel #1
```

**Comment by mickmcgrath13** [comment]
What makes this happen?
```
DEBUG notifier [-] Processing liveaction 594aad3f271fb24e06469e47 (live_action_db={'status': u'canceled', 'runner_info': {u'hostname': u'my-host-name.com', u'pid': 19838}, 'parameters': {u'email_address': u'r.w@gmail.com', u'parent_execution_id': u'poarent_exec_id', u'error_code': u'1234'}, 'action_is_workflow': True, 'start_timestamp': '2017-06-21 17:30:39.507751+00:00', 'callback': {}, 'notify': None, 'result': {'tasks': [{'state_info': None, 'name': u'delegate', 'workflow_name': u'default.sre-demo-error-notifier', 'created_at': u'2017-06-21 17:30:40', 'updated_at': None, 'workflow_execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af', 'state': u'RUNNING', 'result': [], 'published': {}, 'input': None, 'id': u'd145eb29-502b-491e-85fc-9e016139060f'}], u'result': None, 'extra': {'state_info': None, 'state': u'CANCELLED'}}, 'context': {u'user': u'ryan', u'mistral': {u'workflow_name': u'default.sre-demo-error-notifier', u'execution_id': u'389d0169-9fa3-483e-a0ca-6c760c08b4af'}}, 'action': u'default.sre-demo-error-notifier', 'id': '594aad3f271fb24e06469e47', 'end_timestamp': '2017-06-21 17:31:15.088020+00:00'})
```

**Comment by mickmcgrath13** [comment]
```
> db.live_action_d_b.find({status: "canceled"})
{ "_id" : ObjectId("594aaa8c271fb24e06469e11"), "status" : "canceled", "start_timestamp" : NumberLong("1498065548615634"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:19:09", "updated_at" : null, "id" : "65521f3b-5be9-4bac-8cdb-d42727e74ec7", "workflow_execution_id" : "1f8a77c7-57a5-4081-9413-68e4fab5f05d", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "1f8a77c7-57a5-4081-9413-68e4fab5f05d" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19869 }, "end_timestamp" : NumberLong("1498065724652571") }
{ "_id" : ObjectId("594aabbc271fb24e06469e36"), "status" : "canceled", "start_timestamp" : NumberLong("1498065852265215"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:24:12", "updated_at" : null, "id" : "45e8b6c7-1dbd-4c42-abb6-9fc1bc9943a7", "workflow_execution_id" : "0ef15a6c-acc1-4213-9907-f2fb64247c3e", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "0ef15a6c-acc1-4213-9907-f2fb64247c3e" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19683 }, "end_timestamp" : NumberLong("1498065901544718") }
{ "_id" : ObjectId("594aac30271fb24e06469e3b"), "status" : "canceled", "start_timestamp" : NumberLong("1498065968749825"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:26:09", "updated_at" : null, "id" : "7ba66943-eabe-42c9-8743-8bbb47560d79", "workflow_execution_id" : "6b36d436-c45a-46f5-a947-9cffd397086f", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "6b36d436-c45a-46f5-a947-9cffd397086f" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19725 }, "end_timestamp" : NumberLong("1498066070726908") }
{ "_id" : ObjectId("594aad3f271fb24e06469e47"), "status" : "canceled", "start_timestamp" : NumberLong("1498066239507751"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:30:40", "updated_at" : null, "id" : "d145eb29-502b-491e-85fc-9e016139060f", "workflow_execution_id" : "389d0169-9fa3-483e-a0ca-6c760c08b4af", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "389d0169-9fa3-483e-a0ca-6c760c08b4af" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19838 }, "end_timestamp" : NumberLong("1498066275088020") }
{ "_id" : ObjectId("594aad6a271fb24e06469e4c"), "status" : "canceled", "start_timestamp" : NumberLong("1498066282605979"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:31:23", "updated_at" : null, "id" : "23d9afa7-94be-4b36-b6d8-db153652cb9b", "workflow_execution_id" : "c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "c03bba5b-cdfc-4ecd-8c6f-dd07e4414b2f" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19896 }, "end_timestamp" : NumberLong("1498066377669612") }
{ "_id" : ObjectId("594aadcf271fb24e06469e51"), "status" : "canceled", "start_timestamp" : NumberLong("1498066383279802"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:33:03", "updated_at" : null, "id" : "650960ac-10f4-403e-b966-298fe7e01107", "workflow_execution_id" : "93d81384-d30c-461f-ad31-95c1ebf15b9b", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "93d81384-d30c-461f-ad31-95c1ebf15b9b" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19704 }, "end_timestamp" : NumberLong("1498066435773204") }
{ "_id" : ObjectId("594aae95271fb24e06469e5d"), "status" : "canceled", "start_timestamp" : NumberLong("1498066581705631"), "action" : "default.sre-demo-error-notifier", "action_is_workflow" : true, "parameters" : { "error_code" : "1234", "parent_execution_id" : "poarent_exec_id", "email_address" : "r.w@gmail.com" }, "result" : { "tasks" : [ { "state_info" : null, "name" : "delegate", "created_at" : "2017-06-21 17:36:22", "updated_at" : null, "id" : "fb2d593d-96ae-422c-b011-a9bf0382768e", "workflow_execution_id" : "8948f34a-43f6-4f2a-8d70-ab134de0f38c", "state" : "RUNNING", "result" : [ ], "published" : {  }, "input" : null, "workflow_name" : "default.sre-demo-error-notifier" } ], "result" : null, "extra" : { "state_info" : null, "state" : "CANCELLED" } }, "context" : { "user" : "ryan", "mistral" : { "workflow_name" : "default.sre-demo-error-notifier", "execution_id" : "8948f34a-43f6-4f2a-8d70-ab134de0f38c" } }, "callback" : {  }, "runner_info" : { "hostname" : "my-host-name.com", "pid" : 19815 }, "end_timestamp" : NumberLong("1498066715707609") }
```

**Comment by mickmcgrath13** [comment]
Deleted those, and now my `sudo tail -f /var/log/st2/st2notifier.log` looks like this:
```
2017-06-23 12:32:35,076 140249212217616 DEBUG base [-] Looking for jobs to run
2017-06-23 12:32:35,077 140249212218256 INFO base [-] Running job "recover_delayed_executions (trigger: interval[0:05:00], next run at: 2017-06-23 19:32:35 UTC)" (scheduled at 2017-06-23 19:32:35.030654+00:00)
2017-06-23 12:32:35,083 140249212217616 DEBUG base [-] Next wakeup is due at 2017-06-23 12:37:35.030654-07:00 (in 299.953799 seconds)
2017-06-23 12:32:35,083 140249212218256 INFO base [-] Job "recover_delayed_executions (trigger: interval[0:05:00], next run at: 2017-06-23 19:37:35 UTC)" executed successfully
```

**Comment by mickmcgrath13** [comment]
Prior, we also did this:
```
db.trace_d_b.drop()
```
and
```
db.trigger_instance_d_b.drop()
```

..which helped clear the cpu as well

**Comment by mickmcgrath13** [comment]
This issue happened (cpu soaring), again, and simply deleting all of these:
```
> db.live_action_d_b.find({status: "canceled"})
```
...resolved it.  

It seems that a live_action with a status of "canceled" can cause problems?


```
$ st2 --version
st2 2.2.1
```

Let me know if you need any further info

**Comment by armab** [comment]
As @bigmstone noted It make sense to update to latest `v2.3.0`.
In latest @lakshmi-kannan and @m4dcoder fixed a lot of CPU-related issues we hit in StackStorm infra ourselves.

It's not clear if they're related comparing to what you're experiencing, but will help to isolate it, comparing to what was already fixed.

**Comment by mickmcgrath13** [comment]
Okay, thanks.  I will look into upgrading when we have the opportunity, and I'll let you know if we run into the issue again.

**Comment by armab** [comment]
Not an issue anymore, since v2.7.0 StackStorm + Mistral integration changed from poll-based to hook-based, releasing the load from the `st2notifier` service.
See CHANGELOG: https://github.com/StackStorm/st2/releases/tag/v2.7.0
